jobs:
  build:
    docker:
      - image: "circleci/node:12.9.1-browsers"
    steps:
      - checkout
      - run: "yarn install"
      - run: "yarn test"
      - store_test_results:
          path: coverage
    working_directory: ~/repo
version: 2.1
