version: 2
jobs:
  build:
    docker:
      - image: cypress/base:6
    working_directory: ~/app
    steps:
      - checkout
      - run: yarn install
      # run unit tests
      - run: yarn test
      - run:
          name: Background the app
          command: yarn start
          background: true
      - run:
          name: Run E2E tests
          command: $(npm bin)/cypress run --record
          when: on_success
