defaults: &defaults
  docker:
    - image: cypress/base:12.16.1
  working_directory: ~/repo

version: 2.1
jobs:
  test-webapp:
    <<: *defaults
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Install serve
          command: yarn global add serve
      - run:
          name: Install dependencies
          command: yarn install
      - run:
          name: Generate build test
          command: yarn build
      - run:
          name: Cypress Test
          command: yarn cy:run

workflows:
  version: 2.1
  build:
    jobs:
      - test-webapp
