jobs:
  build:
    docker:
      - image: "circleci/node:12.9.1-browsers"
    steps:
      - checkout
      - run: "yarn install"
      - run: "yarn test"
      - store_artifacts:
          path: cypress/videos
      - store_artifacts:
          path: cypress/screenshots
      - store_artifacts:
          path: coverage
      - store_test_results:
          path: results
    working_directory: ~/repo
version: 2.1
