version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build-and-test:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
            - run: npm i serve
            - run: npm run build
            - run: npm run cy:run
workflows:
  build-and-test:
    jobs:
      - build-and-test
