jobs:
  build:
    docker:
      - image: "circleci/node:12.9.1-browsers"
    steps:
      - checkout
      - run: "yarn install"
      - run: "yarn lint"
      - run: "yarn size"
      - run: "yarn test"
    working_directory: ~/repo
orbs:
  cypress: cypress-io/cypress@1.23.0
version: 2.1
