version: 2.1
orbs:
  node: circleci/node@1.1.6
  cypress: cypress-io/cypress@1
jobs:
  build-and-test:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
workflows:
  build:
    - cypress/run:
        yarn: true
        start: yarn start
        wait-on: "http://localhost:3000"
        no-workspace: true
