jobs:
  build:
    docker:
      - image: "circleci/node:12.9.1-browsers"
    steps:
      - checkout
      - run: "yarn install"
      - run: "yarn start"
    working_directory: ~/repo
    jobs:
      - cypress/run:
          config: "pageLoadTimeout=100000,watchForFileChanges=false"
orbs:
  cypress: cypress-io/cypress@1.23.0
version: 2.1
